services:
  docker_proxy:
    image: docker.io/tecnativa/docker-socket-proxy:latest
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: docker_proxy-{{.Service.ID}}
    environment:
      INFO: 1 # Caddy-Docker-Proxy
      SWARM: 1 # Caddy-Docker-Proxy
      TASKS: 1 # Caddy-Docker-Proxy
      EVENTS: 1 # Caddy-Docker-Proxy
      CONFIGS: 1 # Caddy-Docker-Proxy
      NETWORKS: 1 # Caddy-Docker-Proxy
      SERVICES: 1 # Caddy-Docker-Proxy
      CONTAINERS: 1 # Caddy-Docker-Proxy
    healthcheck:
      test: wget --timeout=1 --tries=1 -q 'http://localhost:2375/_ping' -O /dev/null
      retries: 3
      timeout: 2s
      interval: 10s
      start_period: 1s
