# yaml-language-server: $schema=https://github.com/Relativ-IT/Butane-Schemas/raw/refs/heads/main/v1.6.0/butane-v1.6.0.json

storage:
  disks:
    - device: /dev/sda
      partitions:
        - label: bios
          number: 1
          size_mib: 1
          type_guid: 21686148-6449-6E6F-744E-656564454649 # BIOS Boot Partition
        - label: esp
          number: 2
          size_mib: 127
          type_guid: C12A7328-F81F-11D2-BA4B-00A0C93EC93B # EFI System Partition
        - label: boot
          size_mib: 384
          type_guid: BC13C2FF-59E6-4262-A352-B275FD6F7172 # XBOOTLDR Partition
        - label: root
          size_mib: 65536 # 64 GiB
        - label: swap
          size_mib: 6144 # 6 GiB
          type_guid: 0657FD6D-A4AB-43C4-84E5-0933C84B4F4F # Linux Swap
        - label: glusterfs
          size_mib: 0 # Use remaining space
      wipe_table: true
  files:
    # --- Distrobox Configuration ---
    - path: /etc/distrobox.ini
      mode: 0644
      contents:
        inline: "!!include files/distrobox.ini;files/distrobox-oracle.ini"
    # --- ZRAM Configuration ---
    - path: /etc/systemd/zram-generator.conf
      mode: 0644
      contents:
        inline: "!!include files/zram.conf;files/zram.mount.conf"
      overwrite: true
  filesystems:
    - path: /var/mnt/glusterfs
      label: glusterfs
      device: /dev/disk/by-partlabel/glusterfs
      format: btrfs
      mount_options:
        - relatime
        - lazytime
        - compress=zstd
      wipe_filesystem: true
      with_mount_unit: true

systemd:
  units:
    # --- uCore Autorebase Services ---
    - name: ucore-unsigned-autorebase.service
      enabled: true
      contents_local: systemd/ucore-unsigned-autorebase.service
    - name: ucore-signed-autorebase.service
      enabled: true
      contents_local: systemd/ucore-signed-autorebase.service
