# yaml-language-server: $schema=https://github.com/Relativ-IT/Butane-Schemas/raw/refs/heads/main/v1.6.0/butane-v1.6.0.json

storage:
  files:
    # --- Set Hostname ---
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: oracle-seis
      overwrite: true
    # --- NetworkManager Connection Profiles ---
    - path: /etc/NetworkManager/system-connections/enp0s6.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=enp0s6
          type=ethernet
          interface-name=enp0s6

          [ipv4]
          dns=208.67.222.222;
          method=manual
          gateway=10.0.2.1
          address1=10.0.2.40/24
          may-fail=false
          ignore-auto-dns=true

          [ipv6]
          dns=2620:119:35::35;
          method=auto
          addr-gen-mode=eui64
          ignore-auto-dns=true
      overwrite: true
