# yaml-language-server: $schema=https://github.com/Relativ-IT/Butane-Schemas/raw/refs/heads/main/v1.6.0/butane-v1.6.0.json

boot_device:
  luks:
    tpm2: true
  mirror:
    devices:
      - /dev/disk/by-id/nvme-KINGSTON_OM8PDP3256B-A01_50026B7684398C01
      - /dev/disk/by-id/nvme-XPG_GAMMIX_S11_Pro_2L37291Q7CWA

storage:
  disks:
    - device: /dev/disk/by-id/coreos-boot-disk # /dev/disk/by-id/nvme-KINGSTON_OM8PDP3256B-A01_50026B7684398C01
      partitions:
        - label: root-1
          size_mib: 242688
    - device: /dev/disk/by-id/nvme-XPG_GAMMIX_S11_Pro_2L37291Q7CWA
      partitions:
        - label: root-2
          size_mib: 242688
      wipe_table: true
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: brasilia-uno
      overwrite: true
    # --- NetworkManager Connection Profiles ---
    # This is the main bridge interface that holds the IP configuration.
    - path: /etc/NetworkManager/system-connections/vmbr0.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=vmbr0
          type=bridge
          interface-name=vmbr0

          [bridge]
          # Enable IGMP (IPv4) and MLD (IPv6) snooping for multicast traffic efficiency.
          multicast-snooping=true

          [ipv4]
          dns=208.67.222.222;
          method=manual
          gateway=192.168.0.1
          address1=192.168.0.253/23

          [ipv6]
          dns=2620:119:35::35;
          method=auto
          addr-gen-mode=eui64
          ignore-auto-dns=true
      overwrite: true
    # --- Bridge Port Configurations ---
    # Each physical interface is enslaved to the vmbr0 bridge.
    # They do not have their own IP configuration.
    - path: /etc/NetworkManager/system-connections/enp0s31f6.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=enp0s31f6-port
          type=ethernet
          interface-name=enp0s31f6
          master=vmbr0
          slave-type=bridge

          [ipv4]
          method=disabled

          [ipv6]
          method=disabled
      overwrite: true
    - path: /etc/NetworkManager/system-connections/enp1s0.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=enp1s0-port
          type=ethernet
          interface-name=enp1s0
          master=vmbr0
          slave-type=bridge

          [ipv4]
          method=disabled

          [ipv6]
          method=disabled
      overwrite: true
    - path: /etc/NetworkManager/system-connections/enp7s0.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=enp7s0-port
          type=ethernet
          interface-name=enp7s0
          master=vmbr0
          slave-type=bridge

          [ipv4]
          method=disabled

          [ipv6]
          method=disabled
      overwrite: true
    - path: /etc/NetworkManager/system-connections/enp8s0.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=enp8s0-port
          type=ethernet
          interface-name=enp8s0
          master=vmbr0
          slave-type=bridge

          [ipv4]
          method=disabled

          [ipv6]
          method=disabled
      overwrite: true
