# yaml-language-server: $schema=https://github.com/Relativ-IT/Butane-Schemas/raw/refs/heads/main/v1.6.0/butane-v1.6.0.json

kernel_arguments:
  should_exist:
    # --- CPU Isolation for LXC Workloads (12th Gen Intel(R) Core(TM) i5-12500T) ---
    # Isolate CPUs 2-11 from the host scheduler for exclusive container use.
    - isolcpus=2,3,4,5,6,7,8,9,10,11
    # Stop the scheduler tick on isolated cores to eliminate jitter.
    - nohz_full=2,3,4,5,6,7,8,9,10,11
    # Offload Read-Copy-Update callbacks from the isolated CPUs.
    - rcu_nocbs=2,3,4,5,6,7,8,9,10,11
    # Confine all hardware interrupts to the non-isolated CPUs (0 & 1).
    - irqaffinity=0,1
    # Provide a hint to the tuned daemon about which CPUs are not isolated.
    # The mask 00000003 corresponds to binary 11, representing CPUs 0 and 1.
    - tuned.non_isolcpus=00000003

storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: brasilia-uno
      overwrite: true

    # --- NetworkManager Connection Profiles ---
    # This is the main bridge interface that holds the IP configuration.
    - path: /etc/NetworkManager/system-connections/vmbr0.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=vmbr0
          type=bridge
          interface-name=vmbr0

          [bridge]
          # Enable IGMP (IPv4) and MLD (IPv6) snooping for multicast traffic efficiency.
          multicast-snooping=true

          [ipv4]
          method=manual
          address1=192.168.0.253/23
          gateway=192.168.0.1

          [ipv6]
          method=auto
          accept-ra=true
          addr-gen-mode=eui64
      overwrite: true

    # --- Bridge Port Configurations ---
    # Each physical interface is enslaved to the vmbr0 bridge.
    # They do not have their own IP configuration.
    - path: /etc/NetworkManager/system-connections/enp0s31f6.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=enp0s31f6-port
          type=ethernet
          interface-name=enp0s31f6
          master=vmbr0
          slave-type=bridge

          [ipv4]
          method=disabled

          [ipv6]
          method=disabled
      overwrite: true

    - path: /etc/NetworkManager/system-connections/enp1s0.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=enp1s0-port
          type=ethernet
          interface-name=enp1s0
          master=vmbr0
          slave-type=bridge

          [ipv4]
          method=disabled

          [ipv6]
          method=disabled
      overwrite: true

    - path: /etc/NetworkManager/system-connections/enp7s0.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=enp7s0-port
          type=ethernet
          interface-name=enp7s0
          master=vmbr0
          slave-type=bridge

          [ipv4]
          method=disabled

          [ipv6]
          method=disabled
      overwrite: true

    - path: /etc/NetworkManager/system-connections/enp8s0.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=enp8s0-port
          type=ethernet
          interface-name=enp8s0
          master=vmbr0
          slave-type=bridge

          [ipv4]
          method=disabled

          [ipv6]
          method=disabled
      overwrite: true
