# yaml-language-server: $schema=https://github.com/Relativ-IT/Butane-Schemas/raw/refs/heads/main/v1.6.0/butane-v1.6.0.json

boot_device:
  luks:
    tpm2: true
    discard: true
  mirror:
    devices:
      - /dev/disk/by-id/nvme-SA2000M8_250G_20001
      - /dev/disk/by-id/nvme-ADATA_SX8200NP_2I2820030266

storage:
  disks:
    - device: /dev/disk/by-id/nvme-SA2000M8_250G_20001
      partitions:
        - label: root-1
          size_mib: 243680 # 238 GiB
      wipe_table: true
    - device: /dev/disk/by-id/nvme-ADATA_SX8200NP_2I2820030266
      partitions:
        - label: root-2
          size_mib: 243680 # 238 GiB
        - label: swap
          size_mib: 8192 # 8 GiB
          type_guid: 0657FD6D-A4AB-43C4-84E5-0933C84B4F4F # Linux Swap
        - label: data
          size_mib: 0 # Use remaining space
      wipe_table: true
  files:
    # --- Set Hostname ---
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: itaipava-uno
      overwrite: true
    - path: /etc/machine-info
      mode: 0644
      contents:
        inline: |
          CHASSIS=server
          PRETTY_HOSTNAME=Itaipava Server Uno
    # --- ZRAM Configuration ---
    - path: /etc/systemd/zram-generator.conf
      mode: 0644
      contents:
        inline: "!!include etc/zram.conf;etc/zram.mount.conf"
      overwrite: true
    # --- NetworkManager Connection Profiles ---
    - path: /etc/NetworkManager/system-connections/enp0s31f6.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=enp0s31f6
          type=ethernet
          interface-name=enp0s31f6

          [ipv4]
          dns=208.67.222.222;
          method=manual
          gateway=192.168.0.1
          address1=192.168.0.254/23
          may-fail=false
          ignore-auto-dns=true

          [ipv6]
          method=auto
          addr-gen-mode=eui64
          dns=2620:119:35::35;
          ignore-auto-dns=true
      overwrite: true
  filesystems:
    - path: /var/mnt/data
      label: data
      device: /dev/disk/by-partlabel/data
      format: btrfs
      mount_options:
        - relatime
        - lazytime
        - compress=zstd
      wipe_filesystem: true
      with_mount_unit: true
