# yaml-language-server: $schema=https://github.com/Relativ-IT/Butane-Schemas/raw/refs/heads/main/v1.6.0/butane-v1.6.0.json

boot_device:
  luks:
    tpm2: true
  mirror:
    devices:
      - /dev/disk/by-id/nvme-SA2000M8_250G_20001
      - /dev/disk/by-id/nvme-ADATA_SX8200NP_2I2820030266

storage:
  disks:
    - device: /dev/disk/by-id/coreos-boot-disk # /dev/disk/by-id/nvme-SA2000M8_250G_20001
      partitions:
        - label: root-1
          size_mib: 242688
    - device: /dev/disk/by-id/nvme-ADATA_SX8200NP_2I2820030266
      partitions:
        - number: 1
          size_mib: 127 # EFI
        - number: 2
          size_mib: 384 # /boot
        - label: root-2
          size_mib: 242688
      wipe_table: true
  files:
    # --- Set Hostname ---
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: itaipava-uno
      overwrite: true
    # --- NetworkManager Connection Profiles ---
    - path: /etc/NetworkManager/system-connections/enp0s31f6.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=enp0s31f6
          type=ethernet
          interface-name=enp0s31f6

          [ipv4]
          dns=208.67.222.222;
          method=manual
          gateway=192.168.0.1
          address1=192.168.0.254/23
          may-fail=false
          ignore-auto-dns=true

          [ipv6]
          method=auto
          addr-gen-mode=eui64
          dns=2620:119:35::35;
          ignore-auto-dns=true
      overwrite: true
