# yaml-language-server: $schema=https://github.com/Relativ-IT/Butane-Schemas/raw/refs/heads/main/v1.6.0/butane-v1.6.0.json

storage:
  files:
    # --- Set Hostname ---
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: itaipava-uno
      overwrite: true

    # --- Bridge Port Configuration ---
    # The physical interface is enslaved to the vmbr0 bridge.
    - path: /etc/NetworkManager/system-connections/enp0s31f6.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=enp0s31f6
          type=ethernet
          interface-name=enp0s31f6

          [ipv4]
          dns=208.67.222.222;
          method=manual
          gateway=192.168.0.1
          address1=192.168.0.254/23
          may-fail=false
          ignore-auto-dns=true

          [ipv6]
          method=auto
          addr-gen-mode=eui64
          dns=2620:119:35::35;
          ignore-auto-dns=true
      overwrite: true
