# syntax=container/containerfile:1.4

FROM alpine:3.22

RUN <<EOF

# Enable custom repositories for GlusterFS
wget -O /etc/apk/keys/ck-6787e0df.rsa.pub https://kohlschuetter.github.io/alpine-repo/keys/ck-6787e0df.rsa.pub
echo "https://kohlschuetter.github.io/alpine-repo" >> /etc/apk/repositories
echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

# Install basic packages
apk add \
    bash \
    bash-completion \
    docker \
    docker-cli-compose \
    glusterfs \
    kitty-terminfo \
    micro \
    openrc \
    tzdata \
    util-linux-misc

# Cleanup openrc to not interfere with the host
sed -i 's/^\(tty\d\:\:\)/#\1/g' /etc/inittab
sed -i \
  -e "/rc_cgroup_mode=/s/^#//g" \
  -e 's/#rc_env_allow=".*"/rc_env_allow="\*"/g' \
  -e 's/#rc_crashed_stop=.*/rc_crashed_stop=NO/g' \
  -e 's/#rc_crashed_start=.*/rc_crashed_start=YES/g' \
  -e 's/#rc_provide=".*"/rc_provide="loopback net"/g' \
  /etc/rc.conf

# Enable cgroups in openrc
rc-update add cgroups

# Configure docker remap user
id -u dockremap &>/dev/null || adduser -SDHs /sbin/nologin dockremap;
# Configure docker remap group
getent group dockremap &>/dev/null || addgroup -S dockremap

# Configure dockremap user and group ids
echo dockremap:$(cat /etc/passwd|grep dockremap|cut -d: -f3):65536 > /etc/subuid
echo dockremap:$(cat /etc/passwd|grep dockremap|cut -d: -f4):65536 > /etc/subgid

# Configure docker daemon
mkdir -p /etc/docker
echo "{" > /etc/docker/daemon.json
echo "  \"mtu\": 1280," >> /etc/docker/daemon.json
echo "  \"ipv6\": true," >> /etc/docker/daemon.json
echo "  \"ip6tables\": true," >> /etc/docker/daemon.json
echo "  \"userland-proxy\": true," >> /etc/docker/daemon.json
echo "  \"userns-remap\": \"dockremap\"" >> /etc/docker/daemon.json
echo "}" >> /etc/docker/daemon.json

# Enable docker in openrc
rc-update add docker default
EOF

COPY entrypoint.sh /usr/local/bin/

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

LABEL org.opencontainers.image.title="dind" \
      org.opencontainers.image.authors="Vítor Vasconcellos <vasconcellos.dev@gmail.com>" \
      org.opencontainers.image.revision="1" \
      org.opencontainers.image.licenses="GPL-3.0" \
      org.opencontainers.image.description="Alpine based Docker-in-Docker (DinD) service container with Docker CLI, Docker Compose v2 and GlusterFS client"
