# yaml-language-server: $schema=https://github.com/Relativ-IT/Butane-Schemas/raw/refs/heads/main/v1.6.0/butane-v1.6.0.json

storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: oracle-uno
    # --- NetworkManager Connection Profiles ---
    - path: /etc/NetworkManager/system-connections/enp0s6.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=enp0s6
          type=ethernet
          interface-name=enp0s6

          [ipv4]
          address1=10.0.0.44/24
          gateway=10.0.0.1
          may-fail=false
          method=manual

          [ipv6]
          addr-gen-mode=eui64
          address1=2603:c028:300:1010:e1b6:f1a9:e2b9:dbb6/64
          gateway6=fe80::200:17ff:fecf:4f27
          method=manual
          accept-ra=2
