configs:
  vaultwarden:
    file: ../configs/vaultwarden/vaultwarden.sh

volumes:
  vaultwarden_data:
    driver: glusterfs
    driver_opts:
      subdir: vaultwarden
  vaultwarden_cache: {}

services:
  vaultwarden:
    build:
      x-bake:
        pull: true
        contexts:
          utilities: ./utilities
        platforms:
          - linux/amd64
          - linux/arm64
      context: .
      network: host
    image: ghcr.io/heavenvolkoff/homelab/vaultwarden:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          memory: 64M
    configs:
      - source: vaultwarden
        target: /etc/vaultwarden.sh
    volumes:
      - type: volume
        target: /data
        source: vaultwarden_data
      - type: volume
        target: /data/icon_cache
        source: vaultwarden_cache
    hostname: vaultwarden-{{.Service.ID}}
    environment:
      DOMAIN: https://vaultwarden.${DOMAIN:?Missing domain}
      LOG_LEVEL: warn
      IP_HEADER: X-Forwarded-For
      SMTP_HOST: ${SMTP_HOST:?Missing smtp host}
      SMTP_PORT: ${SMTP_PORT:?Missing smtp port}
      SMTP_FROM: vaultwarden@mail.${DOMAIN:?Missing domain}
      ROCKET_ENV: production
      ROCKET_PORT: 8080
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN:?Missing vaultwarden admin token}
      DATABASE_URL: mysql://${VAULTWARDEN_DB_USER:?Missing vaultwarden database user}:${VAULTWARDEN_DB_PASS:?Missing vaultwarden database password}@maria_db/bitwarden
      SMTP_USERNAME: ${SMTP_USER:?Missing smtp username}
      SMTP_PASSWORD: ${SMTP_PASS:?Missing smtp password}
      SMTP_FROM_NAME: Vasconcellos Vaultwarden
      SIGNUPS_VERIFY: "false"
      RUST_BACKTRACE: 1
      ROCKET_WORKERS: 6
      SIGNUPS_ALLOWED: "false"
      EXTENDED_LOGGING: "true"
      WEB_VAULT_ENABLED: "false"
      WEBSOCKET_ENABLED: "true"
      SHOW_PASSWORD_HINT: "false"
      INVITATION_ORG_NAME: Vasconcellos Vaultwarden
      INVITATIONS_ALLOWED: "true"
