services:
  shoko:
    image: docker.io/shokoanime/server:daily@sha256:7874204a4b9b7e05724c80a67826ee061e73901f7b8ff9d2abfd58dd3df8e776
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
        reservations:
          memory: 200M
    volumes:
      - ${MEDIA_DIR:?Missing media dir}:/media/Animes:/media/Animes
      - ${ROOT_DIR:?Missing root dir}/runtime/shoko:/home/shoko/.shoko
    hostname: shoko-{{.Service.ID}}
    environment:
      AVDUMP_MONO: "true"
