services:
  shoko:
    image: docker.io/shokoanime/server:daily@sha256:d528178220d81dfc782e96e99393e6b2bb572eaedbae08389c82bc8a369b5cd2
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
        reservations:
          memory: 200M
    volumes:
      - ${MEDIA_DIR:?Missing media dir}:/media/Animes:/media/Animes
      - ${ROOT_DIR:?Missing root dir}/runtime/shoko:/home/shoko/.shoko
    hostname: shoko-{{.Service.ID}}
    environment:
      AVDUMP_MONO: "true"
