services:
  shoko:
    image: docker.io/shokoanime/server:daily@sha256:f2c75d8db16dda9d4f942552cec5be729675adfb3aadcc697a9ac940605d3f46
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
        reservations:
          memory: 200M
    volumes:
      - ${MEDIA_DIR:?Missing media dir}:/media/Animes:/media/Animes
      - ${ROOT_DIR:?Missing root dir}/runtime/shoko:/home/shoko/.shoko
    hostname: shoko-{{.Service.ID}}
    environment:
      AVDUMP_MONO: "true"
