# syntax=container/containerfile:1.4

FROM alpine:edge

RUN --mount=type=bind,source=./install.sh,target=/tmp/install.sh \
    --mount=type=cache,target=/var/cache/apk \
    /tmp/install.sh

COPY entrypoint.sh /usr/local/bin/

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

LABEL org.opencontainers.image.title="dinp" \
      org.opencontainers.image.authors="Vítor Vasconcellos <vasconcellos.dev@gmail.com>" \
      org.opencontainers.image.revision="1" \
      org.opencontainers.image.licenses="GPL-3.0" \
      org.opencontainers.image.description="Alpine based Docker-in-Podman (DinP) service container with Docker CLI, Docker Compose v2 and GlusterFS client"
