# cSpell:ignore JELLYFIN_NOWEBCONTENT

volumes:
  jellyfin_cache: {}
  jellyfin_transcodes: {}

services:
  jellyfin:
    build:
      x-bake:
        pull: true
        contexts:
          utilities: ./utilities
        platforms:
          - linux/amd64
          - linux/arm64
      context: .
      network: host
    image: ghcr.io/${REGISTRY_USER:-heavenvolkoff}/homelab/jellyfin:latest
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G
        reservations:
          memory: 512M
    volumes:
      - ${MEDIA_DIR:?Missing media dir}:/media
      - ${ROOT_DIR:?Missing root dir}/runtime/jellyfin/config:/etc/jellyfin
      - ${ROOT_DIR:?Missing root dir}/runtime/jellyfin/data:/usr/share/jellyfin
      - type: volume
        source: jellyfin_cache
        target: /var/cache/jellyfin
      - type: volume
        source: jellyfin_transcodes
        target: /tmp/transcodes
    hostname: jellyfin-{{.Service.ID}}
    environment:
      JELLYFIN_URL: https://jellyfin.${DOMAIN:?Missing domain}
      JELLYFIN_NOWEBCONTENT: "true"
