# cSpell:ignore trurl truser trpass

services:
  flood:
    build:
      x-bake:
        pull: true
        contexts:
          utilities: ./utilities
        platforms:
          - linux/amd64
          - linux/arm64
      context: .
      network: host
    image: ghcr.io/${REGISTRY_USER:-heavenvolkoff}/homelab/flood:latest
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 512M
        reservations:
          memory: 128M
    command:
      - --auth=none
      - --host=0.0.0.0
      - --trurl=http://transmission:9091/transmission/rpc
      - --truser=${TRANSMISSION_RPC_USER:?Missing transmission rpc user}
      - --trpass=${TRANSMISSION_RPC_PASS:?Missing transmission rpc password}
      - --assets=false
      - --secret=${FLOOD_JWT_SECRET:?Missing flood jwt secret}
    volumes:
      - ${ROOT_DIR:?Missing root dir}/runtime/flood/config:/usr/share/flood
      - ${MEDIA_DIR:?Missing media dir}:/media
      - ${TORRENT_DIR:?Missing torrent dir}:/download
    hostname: flood-{{.Service.ID}}
    environment:
      FLOOD_ALLOWED_DIRS: /media,/download
