# yaml-language-server: $schema=https://github.com/Relativ-IT/Butane-Schemas/raw/refs/heads/main/v1.6.0/butane-v1.6.0.json

kernel_arguments:
  should_exist:
    # --- Performance, Low-Latency & High Availability ---
    # Disable watchdog timers, which are often unnecessary in virtualized environments.
    - nowatchdog
    # Set Transparent Huge Pages to the recommended setting to avoid latency spikes.
    - transparent_hugepage=madvise

storage:
  files:
    # --- System Locale Configuration ---
    - path: /etc/resolv.conf
      mode: 0644
      contents:
        # Use OpenDNS as the default DNS resolver
        inline: |
          nameserver 208.67.222.222
          nameserver 2620:119:35::35
      overwrite: true
  directories:
    - path: /etc/ucore-autorebase
      mode: 0754
    - path: /etc/NetworkManager/system-connections
      mode: 0700
      overwrite: true

systemd:
  units:
    # --- Disable systemd-resolved ---
    - name: systemd-resolved.service
      enabled: false
    # --- Enable Tailscale ---
    - name: tailscaled.service
      enabled: true
    # --- Enable tuned ---
    - name: tuned.service
      enabled: true
    - name: tuned-profile.service
      enabled: true
      contents: "!!include systemd/tuned-profile.service"
