# yaml-language-server: $schema=https://github.com/Relativ-IT/Butane-Schemas/raw/refs/heads/main/v1.6.0/butane-v1.6.0.json

# cSpell:ignore nowatchdog dinp pythonrc

kernel_arguments:
  should_exist:
    # --- Performance, Low-Latency & High Availability ---
    # Disable watchdog timers, which are often unnecessary in virtualized environments.
    - nowatchdog
    # Set Transparent Huge Pages to the recommended setting to avoid latency spikes.
    - transparent_hugepage=madvise
    # Required for docker to be able to assign swap memory to containers.
    - cgroup_enable=memory
    - swapaccount=1

storage:
  directories:
    - path: /etc/ucore-autorebase
      mode: 0754
    - path: /home/core/.local
      mode: 0750
      user: { name: core }
      group: { name: core }
    - path: /home/core/.local/share
      mode: 0750
      user: { name: core }
      group: { name: core }
    - path: /home/core/.local/gnupg
      mode: 0700
      user: { name: core }
      group: { name: core }
    - path: /home/core/.local/state
      mode: 0750
      user: { name: core }
      group: { name: core }
    - path: /home/core/.local/state/bash
      mode: 0750
      user: { name: core }
      group: { name: core }
    - path: /home/core/.config
      mode: 0750
      user: { name: core }
      group: { name: core }
    - path: /home/core/.config/python
      mode: 0750
      user: { name: core }
      group: { name: core }
    - path: /home/core/.config/readline
      mode: 0750
      user: { name: core }
      group: { name: core }
    - path: /home/core/.config/environment.d
      mode: 0750
      user: { name: core }
      group: { name: core }
    - path: /etc/NetworkManager/system-connections
      mode: 0700
      overwrite: true
  files:
    # --- System Locale Configuration ---
    - path: /etc/resolv.conf
      mode: 0644
      contents:
        # Use OpenDNS as the default DNS resolver
        inline: |
          nameserver 208.67.222.222
          nameserver 2620:119:35::35
      overwrite: true
    # --- CoreOS live environment GRUB setup script ---
    - path: /usr/local/bin/coreos-live-setup
      mode: 0750
      contents:
        local: files/coreos-live-setup.sh
    # --- Firewall setup script ---
    - path: /usr/local/bin/setup-firewall
      mode: 0750
      contents:
        local: files/setup-firewall.sh
    # --- Docker-in-Podman container ---
    - path: /etc/containers/systemd/dualstack.network
      mode: 0750
      contents:
        local: files/dualstack.network
    - path: /etc/containers/systemd/dinp.volume
      mode: 0750
      contents:
        local: files/dinp.volume
    - path: /etc/containers/systemd/dinp.container
      mode: 0750
      contents:
        local: files/dinp.container
    # --- XDG env var configuration ---
    - path: /home/core/.config/environment.d/00-xdg.conf
      mode: 0640
      user: { name: core }
      group: { name: core }
      contents:
        local: files/xdg.conf
    # --- Sensible Bash configuration ---
    - path: /home/core/.local/share/sensible.bash
      mode: 0640
      user: { name: core }
      group: { name: core }
      contents:
        local: files/sensible.bash
    # --- User bashrc ---
    - path: /home/core/.bashrc
      mode: 0640
      user: { name: core }
      group: { name: core }
      contents:
        local: files/bashrc.sh
      overwrite: true
    # --- Starship configuration ---
    - path: /home/core/.config/starship.toml
      mode: 0640
      user: { name: core }
      group: { name: core }
      contents:
        local: files/starship.toml
    # --- Python history configuration ---
    - path: /home/core/.config/python/pythonrc
      mode: 0640
      user: { name: core }
      group: { name: core }
      contents:
        local: files/rc.py

systemd:
  units:
    # --- Disable systemd-resolved ---
    - name: systemd-resolved.service
      enabled: false
    # --- Enable tuned ---
    - name: tuned.service
      enabled: true
    - name: tuned-profile.service
      enabled: true
      contents_local: systemd/tuned-profile.service
