# yaml-language-server: $schema=https://github.com/Relativ-IT/Butane-Schemas/raw/refs/heads/main/v1.6.0/butane-v1.6.0.json

kernel_arguments:
  should_exist:
    # --- Performance, Low-Latency & High Availability ---
    # Disable watchdog timers, which are often unnecessary in virtualized environments.
    - nowatchdog
    # Set Transparent Huge Pages to the recommended setting to avoid latency spikes.
    - transparent_hugepage=madvise
    # Required for docker to be able to assign swap memory to containers.
    - cgroup_enable=memory
    - swapaccount=1

storage:
  directories:
    - path: /etc/ucore-autorebase
      mode: 0754
    - path: /home/core/.config/environment.d
      mode: 0750
      user: { name: core }
      group: { name: core }
    - path: /etc/NetworkManager/system-connections
      mode: 0700
      overwrite: true
  files:
    # --- System Locale Configuration ---
    - path: /etc/resolv.conf
      mode: 0644
      contents:
        # Use OpenDNS as the default DNS resolver
        inline: |
          nameserver 208.67.222.222
          nameserver 2620:119:35::35
      overwrite: true
    # --- CoreOS live environment GRUB setup script ---
    - path: /usr/local/bin/coreos-live-setup
      mode: 0750
      contents:
        inline: "!!include files/coreos-live-setup.sh"
    # --- XDG env var configuration ---
    - path: /home/core/.config/environment.d/00-xdg.conf
      mode: 0640
      user: { name: core }
      group: { name: core }
      contents:
        inline: "!!include files/xdg.conf"
    # --- Sensible Bash configuration ---
    - path: /home/core/.local/share/sensible.bash
      mode: 0640
      user: { name: core }
      group: { name: core }
      contents:
        inline: "!!include files/sensible.bash"
    # --- User bashrc ---
    - path: /home/core/.bashrc
      mode: 0640
      user: { name: core }
      group: { name: core }
      contents:
        inline: "!!include files/bashrc.sh"
      overwrite: true
    # --- Starship configuration ---
    - path: /home/core/.config/starship.toml
      mode: 0640
      user: { name: core }
      group: { name: core }
      contents:
        inline: "!!include files/starship.toml"

systemd:
  units:
    # --- Disable systemd-resolved ---
    - name: systemd-resolved.service
      enabled: false
    # --- Enable Tailscale ---
    - name: tailscaled.service
      enabled: true
    # --- Enable tuned ---
    - name: tuned.service
      enabled: true
    - name: tuned-profile.service
      enabled: true
      contents: "!!include systemd/tuned-profile.service"
