name: Build butane files

on:
  workflow_dispatch:
  push:
    paths:
      - "butane/**"
    branches:
      - "main"
  pull_request:
    paths:
      - "butane/**"

# Cancel previous runs of the same workflow on the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ignition:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install dependencies
        shell: bash
        run: |
          sudo parallel --xapply curl -fsSL -o /usr/local/bin/{1} https://github.com/{2}/{1}/releases/latest/download/{1}{3} \
            ::: yq butane ::: mikefarah coreos ::: _linux_amd64 -x86_64-unknown-linux-gnu
          sudo chmod +x /usr/local/bin/yq /usr/local/bin/butane
      - name: Build butane files
        shell: bash
        run: env CORE_PASSHASH='${{ secrets.CORE_PASSHASH }}' ./butane/build.sh
      - name: Upload ignition files to Gist
        shell: bash
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          set -euo pipefail

          gist="$(mktemp "${TMPDIR:-/tmp}/ist.XXXXXX")"
          trap 'rm -f "$gist"' EXIT

          pushd "$gist"

          git init
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote add origin 'https://${{ secrets.GIST_TOKEN }}@gist.github.com/${{ secrets.GIST_ID }}.git'
          git fetch -apP --all
          git checkout main

          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

          popd

          rsync -aP butane/output/ "$gist/"

          pushd "$gist"

          git add -A
          if ! git diff-index --quiet HEAD --; then
            git commit -am "Update ignition files"
            git push origin main
          fi
