name: Containers

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  REGISTRY_IMAGE: ghcr.io/HeavenVolkoff/homelab

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.generate.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Symlink .env
        run: ln -s .env.example .env
      - name: List targets
        id: generate
        uses: docker/bake-action/subaction/list-targets@v4
        with:
          target: ubuntu

  build-containesr:
    name: Build Containers
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
          target: ${{ fromJson(needs.prepare.outputs.targets) }}
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Symlink .env
        run: ln -s .env.example .env
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/bake-action@v5
        with:
          targets: ${{ matrix.target }}
          push: true
          set: |
            *.cache-from=type=gha,scope=${{ matrix.target }}
            *.cache-to=type=gha,mode=max,scope=${{ matrix.target }}
